# Generated by Django 5.0.2 on 2024-02-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[(1, 'Новый'), (2, 'Подтвержден'), (3, 'Собран'), (4, 'Отправлен'), (5, 'Доставлен'), (6, 'Отменен')], max_length=15, verbose_name='Статус'),
        ),
    ]
