# Generated by Django 5.0.2 on 2024-02-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_order_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='url',
        ),
        migrations.AddField(
            model_name='shop',
            name='file',
            field=models.CharField(blank=True, null=True, verbose_name='Файл с прайсом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[(1, 'Новый'), (2, 'Подтвержден'), (3, 'Отправлен')], max_length=15, verbose_name='Статус'),
        ),
    ]
