# Generated by Django 5.0.2 on 2024-03-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shops',
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_shop', to='backend.category', verbose_name='Категория')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_category', to='backend.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Связь категорий и магазинов',
            },
        ),
    ]
