# Generated by Django 5.0.2 on 2024-03-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_category_shops_shopcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productparameter',
            name='parameter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='backend.parameter', verbose_name='Параметр'),
        ),
    ]
