# Generated by Django 5.0.2 on 2024-03-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_productparameter_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=models.CharField(choices=[('not sent', 'Не отправлен'), ('sent', 'Отправлен')], default='not sent', max_length=15, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='adress',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='backend.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('not accepted', 'Не подтвержден'), ('accepted', 'Подтвержден')], max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='backend.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='productparameter',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parameters', to='backend.product', verbose_name='Продукт'),
        ),
    ]
